### ISSUE TITLE
Can you add a option to decode hca from rla?

### ISSUE THREAD

**Issue by Sheep975** [mos9527/sssekai#3]
It's really hard to convert hca without metadata, and I don't know how to make it.

**Comment by mos9527** [comment]
There were some disscussion in a [UnityPy Discord thread](https://discord.com/channels/603359898507673630/1275510423772463125) regarding their (possibly custom) HCA decoding.
TL;DR as of now I have yet  _(nor would be able to anytime soon since its been really busy for me recently^^)_ to  figure out how their HCA codec worked so one of the known ways to decode it is to piggyback the game's CriWare lib to decode it  there instead.
One of the ways to achieve that is through the use of the game's own runtime (through Frida), which is discussed in the discord thread.
There are other solutions like https://github.com/maiyao1988/ExAndroidNativeEmu which I'd like to investigate _sometime_. But then again, no promises for now.

**Comment by Sheep975** [comment]
wow I'll take a look there. Thank you!

**Comment by mos9527** [comment]
Hi! Sorry for the wait!^^

A functional, native (emulated w/[ExAndroidNativeEmu](https://github.com/maiyao1988/ExAndroidNativeEmu)) HCA decoder is now available [here](https://github.com/mos9527/sssekai_streaming_hca_decoder). 
Please take a look at the [updated wiki](https://github.com/mos9527/sssekai/wiki#streaming-live-files) for its usage.

**Comment by Sheep975** [comment]
I had to copy vfs folder from ExAndroidNativeEmu and .so files from sekai apk, but it actually worked! Thank you so much!!

**Comment by mos9527** [comment]
Seems like I forgot to add the binaries😅
For future readers this is fixed. Please refer to the updated installation instructions for more info:https://github.com/mos9527/sssekai_streaming_hca_decoder/tree/master?tab=readme-ov-file#installation
