### ISSUE TITLE
[QUESTION] assetbundle CRC & Hash

### ISSUE THREAD

**Issue by Duosion** [mos9527/sssekai#9]
This is not an issue with sssekai, but a question regarding the data retrieved from the game's assetbundle-info endpoint.

Do you know how the crc and hash values contained within this data for each assetbundle are calculated?

Example excerpt from the JP assetbundle info for version ``4.0.5.20``:
```
{
    "bundleName": "area/area16",
    "cacheFileName": "773649635f5fe7f5a8752b3e1e069447",
    "cacheDirectoryName": "4b82",
    "hash": "4048fd0edd7c9b611a7f100a352101ee",
    "category": "StartApp",
    "crc": 2587611330,
    "fileSize": 1832748,
    "dependencies": [],
    "paths": [
        "StartApp/area/area16",
        "StartApp/area/area16/Material",
        "StartApp/area/area16/Prefab",
        "StartApp/area/area16/Texture"
    ],
    "isBuiltin": false
}
```

I have tried to calculate the ``hash`` value manually using MD5 and MD4 on both encrypted and unencrypted assetbundles, but always receive a different hash value than is reported in the assetbundle info.

If you have a local copy of every assetbundle from version ``4.0.5.10`` and wanted to update that copy to, say, ``4.0.5.20``, knowing this would allow one to only download the assets that changed between versions.

**Comment by mos9527** [comment]
[I assumed the game never updated the files based on their content](https://mos9527.github.io/posts/pjsk/archive-20240105/#1-assetbundleinfo)  - instead they kept track of a *local* version of `AssetBundleInfo`, storing the mapping of *downloaded* ABs (w/ hashes and other stuff) instead.

Decompiled code suggested the same - though I could be missing out on things. I didn't find anything concrete on calculating the downloaded bundles' hashes.

I assume doing so would avoid the extra IO for integrity check since the ones stored are (typically) guaranteed to match the hash values unless otherwise tampered. 

Tbh it might be better to do the updates this way too

**Comment by Duosion** [comment]
I see, so in the scenario that we are updating from asset version ``4.0.5.10`` -> ``4.0.5.20``: 

The game takes the ``AssetBundleInfo`` for version ``4.0.5.10`` and compares the computed hashes for each assetbundle to the new computed hashes in the ``AssetBundleInfo`` for version ``4.0.5.20``, downloading any differences.

It's honestly pretty ingenious.

That makes a lot more sense now, thanks for the clarification on that.

Amazing blog post series by the way. I read that part, but Google Translate made it pretty vague.
